[tool.black]
line-length = 120

[tool.isort]
include_trailing_comma = true
line_length = 120
multi_line_output = 3

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
disallow_untyped_defs = true
