name: "Validate commits"

on: [push]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Apply isort, black and flake8
      run: |
        pip install isort==5.10.1 black==22.1.0 flake8==4.0.1
        isort --check-only .
        black --check .
        flake8
    - name: Run mypy
      run: |
        if [[ `git log -1 --name-only --oneline | grep '.py'` ]]; then
          pip install mypy
          mypy `git log -1 --name-only --oneline | grep '.py'`         
        else
          echo 'no files'
          exit 0
        fi
